import { precacheAndRoute } from 'workbox-precaching';

// Declare self properties so TypeScript knows they exist
declare const self: {
  __WB_MANIFEST: any;
  addEventListener: (type: string, listener: (event: any) => void) => void;
  registration: {
    showNotification: (title: string, options?: any) => Promise<void>;
  };
  clients: {
    matchAll: (options?: any) => Promise<any[]>;
    openWindow: (url: string) => Promise<any>;
  };
};

// Precache resources generated by build - MUST use self.__WB_MANIFEST literally
precacheAndRoute(self.__WB_MANIFEST || []);

// Listen for push notifications
self.addEventListener('push', (event: any) => {
  if (!event.data) return;
  try {
    const payload = event.data.json();
    const options = {
      body: payload.body,
      icon: '/icon.png',
      badge: '/icon.png',
      tag: payload.tag || 'zerolag-notification',
      renotify: true,
      sound: 'default',
      data: {
        url: payload.url || '/'
      }
    };
    
    // Broadcast message to open tabs to play a sound
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients: any[]) => {
      windowClients.forEach((client: any) => {
        client.postMessage({ type: 'PLAY_NOTIFICATION_SOUND' });
      });
    });

    event.waitUntil(
      self.registration.showNotification(payload.title || 'ZeroLag Update', options)
    );
  } catch (e) {
    console.error('Error parsing push event:', e);
  }
});

// Listen for notification clicks
self.addEventListener('notificationclick', (event: any) => {
  event.notification.close();
  const urlToOpen = event.notification.data?.url || '/';
  
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients: any[]) => {
      // If a window is already open at the target URL, focus it
      for (let i = 0; i < windowClients.length; i++) {
        const client = windowClients[i];
        if (client.url === urlToOpen && 'focus' in client) {
          return client.focus();
        }
      }
      // Otherwise, open a new window
      if (self.clients.openWindow) {
        return self.clients.openWindow(urlToOpen);
      }
    })
  );
});
